# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7221702d9840fd8b097b51e1c8a9f5fb4b19696443759a5a4ee47f4e68886e28907dc6935f41b1382772df396c372f7dc11f96892c3c44f3648f8e75260cb6e9

test:
  secret_key_base: d4af14d112da5ba94efbed1d6346a79b6439d143cc71acca7bfeead5c4d38aa74c44ad843598f640f2157b703a887b3d897725bdda299d89bc696238f674d8f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
